# version: '3.9'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-9
    volumes:
      - ./crud:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./crud:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - laravel-network

  mysql:
    image: mysql:8.1.0
    container_name: laravel-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=inter1908
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network
  
  mongo:
    image: mongo:latest
    container_name: laravel-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=inter1908
    volumes:
      - mongo-data:/data/db
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
